#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $HOME/bin
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

# New environment setting added by STAR-CCM+9.02.005 on Wed Mar 11 16:36:40 GMT 2015 1.
# The unmodified version of this file is saved in /home/bit11/.zprofile2104443105.
# Do NOT modify these lines; they are used to uninstall.
PATH="/home/bit11/starccm/STAR-CCM+9.02.005/star/bin:${PATH}"
export PATH
# End comments by InstallAnywhere on Wed Mar 11 16:36:40 GMT 2015 1.

# New environment setting added by STAR-CCM+9.02.005 on Wed Mar 11 16:36:46 GMT 2015 4.
# The unmodified version of this file is saved in /home/bit11/.zprofile2104443105.
# Do NOT modify these lines; they are used to uninstall.
CDLMD_LICENSE_FILE=1999@iclic17.cc.ic.ac.uk:1999@iclic17.cc.ic.ac.uk:1999@iclic17.cc.ic.ac.uk
export CDLMD_LICENSE_FILE
# End comments by InstallAnywhere on Wed Mar 11 16:36:46 GMT 2015 4.

# New environment setting added by STAR-CCM+9.02.005 on Wed Mar 11 16:50:53 GMT 2015 7.
# The unmodified version of this file is saved in /home/bit11/.zprofile2104443105.
# Do NOT modify these lines; they are used to uninstall.
PATH="/home/bit11/starccm/STAR-View+9.02.005:${PATH}"
export PATH
# End comments by InstallAnywhere on Wed Mar 11 16:50:53 GMT 2015 7.
