#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/aliases.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/aliases.zsh"
fi

# Load base16 colours
BASE16_SHELL="$HOME/dotfiles/colours/base16-atelierlakeside.light.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
